pub mod ft_putchar;
pub mod ft_putstr;
pub mod ft_putchar_fd;
pub mod ft_putstr_fd;
pub mod ft_putendl;
pub mod ft_putnbr;
pub mod ft_putendl_fd;
pub mod ft_itoa;
pub mod ft_putnbr_fd;

pub use ft_putchar::ft_putchar;
pub use ft_putstr::ft_putstr;
pub use ft_putchar_fd::ft_putchar_fd;
pub use ft_putstr_fd::ft_putstr_fd;
pub use ft_putendl::ft_putendl;
pub use ft_putendl_fd::ft_putendl_fd;
pub use ft_putnbr::ft_putnbr;
pub use ft_putnbr_fd::ft_putnbr_fd;
pub use ft_itoa::ft_itoa;
