[package]
name = "libft-but-rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[test]]
name = "libft_tests"
path = "src/tests/mod.rs"
